--liquibase formatted sql

--changeset evready:V002-create-charger-type-table
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'charger_type';
CREATE TABLE charger_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR(100),
    CONSTRAINT uk_charger_type_code UNIQUE (code),
    CONSTRAINT uk_charger_type_name UNIQUE (name)
);

CREATE INDEX idx_charger_type_code ON charger_type (code);
CREATE INDEX idx_charger_type_name ON charger_type (name);
CREATE INDEX idx_charger_type_is_active ON charger_type (is_active);
CREATE INDEX idx_charger_type_display_order ON charger_type (display_order);
