--liquibase formatted sql

--changeset evready:V004-create-vehicle-table
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'vehicle';
CREATE TABLE vehicle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_type VARCHAR(20) NOT NULL,
    brand_id BIGINT NOT NULL,
    charger_type_id BIGINT,
    model VARCHAR(150) NOT NULL,
    variant VARCHAR(150),
    price_pkr BIGINT,
    range_km INTEGER,
    battery_capacity_kwh NUMERIC(8,3),
    dc_fast_charging BOOLEAN NOT NULL DEFAULT FALSE,
    image VARCHAR(255),
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL DEFAULT 0,
    source_url VARCHAR(500),
    source_label VARCHAR(150),
    source_checked_at TIMESTAMP WITH TIME ZONE,
    verification_status VARCHAR(30) NOT NULL DEFAULT 'UNVERIFIED',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR(100),
    CONSTRAINT fk_vehicle_brand FOREIGN KEY (brand_id) REFERENCES brand (id),
    CONSTRAINT fk_vehicle_charger_type FOREIGN KEY (charger_type_id) REFERENCES charger_type (id)
);

CREATE INDEX idx_vehicle_vehicle_type ON vehicle (vehicle_type);
CREATE INDEX idx_vehicle_brand_id ON vehicle (brand_id);
CREATE INDEX idx_vehicle_charger_type_id ON vehicle (charger_type_id);
CREATE INDEX idx_vehicle_price_pkr ON vehicle (price_pkr);
CREATE INDEX idx_vehicle_range_km ON vehicle (range_km);
CREATE INDEX idx_vehicle_is_active ON vehicle (is_active);
CREATE INDEX idx_vehicle_display_order ON vehicle (display_order);
