--liquibase formatted sql

--changeset evready:V005-create-charger-table
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'charger';
CREATE TABLE charger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    charger_type_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    city VARCHAR(100) NOT NULL,
    area VARCHAR(150),
    address TEXT,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    charging_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    power_kw NUMERIC(8,2),
    price_note VARCHAR(255),
    description TEXT NOT NULL,
    image VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL DEFAULT 0,
    source_url VARCHAR(500),
    source_label VARCHAR(150),
    source_checked_at TIMESTAMP WITH TIME ZONE,
    verification_status VARCHAR(30) NOT NULL DEFAULT 'UNVERIFIED',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR(100),
    CONSTRAINT fk_charger_charger_type FOREIGN KEY (charger_type_id) REFERENCES charger_type (id)
);

CREATE INDEX idx_charger_charger_type_id ON charger (charger_type_id);
CREATE INDEX idx_charger_city ON charger (city);
CREATE INDEX idx_charger_charging_type ON charger (charging_type);
CREATE INDEX idx_charger_status ON charger (status);
CREATE INDEX idx_charger_is_active ON charger (is_active);
CREATE INDEX idx_charger_display_order ON charger (display_order);
