--liquibase formatted sql

--changeset evready:V006-create-lead-submission-table
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'lead_submission';
CREATE TABLE lead_submission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    city VARCHAR(100),
    interest_type VARCHAR(40) NOT NULL,
    message TEXT,
    source_page VARCHAR(120),
    consent_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    lead_status VARCHAR(40) NOT NULL DEFAULT 'NEW',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR(100)
);

CREATE INDEX idx_lead_submission_interest_type ON lead_submission (interest_type);
CREATE INDEX idx_lead_submission_lead_status ON lead_submission (lead_status);
CREATE INDEX idx_lead_submission_city ON lead_submission (city);
CREATE INDEX idx_lead_submission_is_active ON lead_submission (is_active);
CREATE INDEX idx_lead_submission_created_at ON lead_submission (created_at);
