--liquibase formatted sql

--changeset evready:V007-create-contact-submission-table
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'contact_submission';
CREATE TABLE contact_submission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(160),
    phone VARCHAR(40),
    organization VARCHAR(160),
    inquiry_type VARCHAR(80) NOT NULL,
    message TEXT NOT NULL,
    source_page VARCHAR(120),
    consent_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR(100)
);

CREATE INDEX idx_contact_submission_inquiry_type ON contact_submission (inquiry_type);
CREATE INDEX idx_contact_submission_created_at ON contact_submission (created_at);
