--liquibase formatted sql

--changeset evready:V015-create-vehicle-review-table
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'vehicle_review';
CREATE TABLE vehicle_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL,
    rating INTEGER NOT NULL,
    review_text TEXT,
    display_name VARCHAR(120),
    city VARCHAR(100),
    experience_type VARCHAR(40) NOT NULL,
    review_status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    moderated_at TIMESTAMP WITH TIME ZONE,
    moderated_by VARCHAR(100),
    moderation_reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR(100),
    CONSTRAINT fk_vehicle_review_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicle (id)
);

CREATE INDEX idx_vehicle_review_vehicle_id ON vehicle_review (vehicle_id);
CREATE INDEX idx_vehicle_review_review_status ON vehicle_review (review_status);
CREATE INDEX idx_vehicle_review_created_at ON vehicle_review (created_at);
