--liquibase formatted sql

--changeset evready:V016-create-charger-feedback-table
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'charger_feedback';
CREATE TABLE charger_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    charger_id BIGINT NOT NULL,
    rating INTEGER,
    feedback_type VARCHAR(40) NOT NULL,
    message TEXT,
    display_name VARCHAR(120),
    city VARCHAR(100),
    reported_by_contact VARCHAR(160),
    feedback_status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    reviewed_at TIMESTAMP WITH TIME ZONE,
    reviewed_by VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR(100),
    CONSTRAINT fk_charger_feedback_charger FOREIGN KEY (charger_id) REFERENCES charger (id)
);

CREATE INDEX idx_charger_feedback_charger_id ON charger_feedback (charger_id);
CREATE INDEX idx_charger_feedback_feedback_status ON charger_feedback (feedback_status);
CREATE INDEX idx_charger_feedback_created_at ON charger_feedback (created_at);
